const jsonUrl = "https://Laila72.github.io/Park_data/bhg.json";
const direct = "https://emiljnsan.github.io/bhage_kart/;
const grunnkart = "https://services.geodataonline.no/arcgis/rest/services/Geocache_WMAS_WGS84/GeocacheBasis/MapServer/tile/{z}/{y}/{x}";
const attribution_tag = '©️ Geodata AS, Kartverket, Geovekst og kommunene, OpenStreetMap';
const marker_oransje = "images/icon/marker-icon_park_oransje.png";
const marker_blaa = "marker-icon_park_blaa.png";
const marker_gron = "marker-icon_park_gron.png";
const shadow = "marker-shadow.png";
const testtekst = "test ok"
